


[package]
name = "hexpng"
version = "0.1.0"
authors = ["tshrpl <tshrpl@tutanota.com>"]
edition = "2021"
description = "generate png from hexcode"



[dependencies]
libflate = "~1.2.0"



[dev-dependencies]
image = "~0.24.3"


