


name: test_everything

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  all-jobs:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - name: hexpng tests
      run: cargo test -p hexpng --verbose
    - name: hexpng tests no_std
      run: cargo test -p hexpng --verbose --no-default-features --features "no-std"
    - name: build server
      run: cargo build -p miscutils_server --release --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: hideme_${{ runner.os }}_${{ github.sha }}
        path: target/release/miscutils_server


